// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ForesterCall(arg1:string,arg2:string):Promise<string>;

export function GetSession():Promise<main.SessionInfo>;

export function InitRepository(arg1:string):Promise<main.SessionInfo>;

export function OpenRepository(arg1:string):Promise<main.SessionInfo>;

export function SelectDirectory():Promise<string>;

export function SetLocale(arg1:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
