// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForesterCall(arg1, arg2) {
  return window['go']['main']['App']['ForesterCall'](arg1, arg2);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function InitRepository(arg1) {
  return window['go']['main']['App']['InitRepository'](arg1);
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function ReadThumbCache(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadThumbCache'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WriteThumbCache(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteThumbCache'](arg1, arg2, arg3, arg4);
}
