/**
 * Generate Forester icons for macOS (.icns), Windows (.ico), and Linux (hicolor PNGs).
 * Rasterization deps live in builder/.staging/icon-tools (see generate_forester_icons.sh).
 */
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildForesterIconSvg,
  FORESTER_BUILD_DIR,
  FORESTER_ICONS_DIR,
} from "../../sources/backend/forester/icons/icon-assets.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, "../..");
const iconNodeRoot = process.env.ICON_NODE_ROOT || join(projectRoot, "builder/.staging/icon-tools");
const buildDir = FORESTER_BUILD_DIR;

const require = createRequire(join(iconNodeRoot, "package.json"));
const { Resvg } = require("@resvg/resvg-js");
const pngToIco = require("png-to-ico");

function renderPng(svg, size) {
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: size },
    background: "transparent",
  });
  return resvg.render().asPng();
}

function writePng(path, svg, size) {
  writeFileSync(path, renderPng(svg, size));
}

mkdirSync(buildDir, { recursive: true });

const masterSvg = buildForesterIconSvg(256);
writeFileSync(join(buildDir, "appicon.png"), renderPng(masterSvg, 1024));
console.log(`Wrote ${join(buildDir, "appicon.png")} (1024x1024)`);

const icoSizes = [16, 24, 32, 48, 64, 128, 256];
const exportDir = join(buildDir, "export");
mkdirSync(exportDir, { recursive: true });
for (const size of icoSizes) {
  writePng(join(exportDir, `${size}.png`), masterSvg, size);
}

const ico = await pngToIco(icoSizes.map((size) => join(exportDir, `${size}.png`)));
writeFileSync(join(buildDir, "forester.ico"), ico);
console.log(`Wrote ${join(buildDir, "forester.ico")}`);

const hicolorSizes = [16, 22, 24, 32, 48, 64, 128, 256, 512];
for (const size of hicolorSizes) {
  const dir = join(buildDir, "share/icons/hicolor", `${size}x${size}`, "apps");
  mkdirSync(dir, { recursive: true });
  writePng(join(dir, "forester.png"), masterSvg, size);
}
const scalableDir = join(buildDir, "share/icons/hicolor/scalable/apps");
mkdirSync(scalableDir, { recursive: true });
writeFileSync(join(scalableDir, "forester.svg"), buildForesterIconSvg(256));
console.log(`Wrote Linux hicolor icons (${hicolorSizes.join(", ")}px + scalable SVG)`);

/** macOS .iconset inputs for iconutil (generated by generate_forester_icons.sh). */
const iconsetMap = [
  ["icon_16x16.png", 16],
  ["icon_16x16@2x.png", 32],
  ["icon_32x32.png", 32],
  ["icon_32x32@2x.png", 64],
  ["icon_128x128.png", 128],
  ["icon_128x128@2x.png", 256],
  ["icon_256x256.png", 256],
  ["icon_256x256@2x.png", 512],
  ["icon_512x512.png", 512],
  ["icon_512x512@2x.png", 1024],
];
const iconsetDir = join(buildDir, "AppIcon.iconset");
mkdirSync(iconsetDir, { recursive: true });
for (const [name, size] of iconsetMap) {
  writePng(join(iconsetDir, name), masterSvg, size);
}
console.log(`Wrote AppIcon.iconset under ${FORESTER_ICONS_DIR} (run iconutil on macOS for AppIcon.icns)`);
