// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnownRepo(arg1) {
  return window['go']['main']['App']['AddKnownRepo'](arg1);
}

export function ForesterCall(arg1, arg2) {
  return window['go']['main']['App']['ForesterCall'](arg1, arg2);
}

export function GetCurrentRepoPath() {
  return window['go']['main']['App']['GetCurrentRepoPath']();
}

export function GetForesterBinaryPath() {
  return window['go']['main']['App']['GetForesterBinaryPath']();
}

export function GetKnownRepos() {
  return window['go']['main']['App']['GetKnownRepos']();
}

export function GetRepoUser() {
  return window['go']['main']['App']['GetRepoUser']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InitRepository(arg1) {
  return window['go']['main']['App']['InitRepository'](arg1);
}

export function InitRepositoryWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitRepositoryWithOptions'](arg1, arg2, arg3);
}

export function IsForesterRepository(arg1) {
  return window['go']['main']['App']['IsForesterRepository'](arg1);
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function PickRepositoryFolder() {
  return window['go']['main']['App']['PickRepositoryFolder']();
}

export function PickSettingsFile() {
  return window['go']['main']['App']['PickSettingsFile']();
}

export function PickSettingsFolder() {
  return window['go']['main']['App']['PickSettingsFolder']();
}

export function RemoveKnownRepo(arg1) {
  return window['go']['main']['App']['RemoveKnownRepo'](arg1);
}

export function SaveSettingsAppearance(arg1, arg2) {
  return window['go']['main']['App']['SaveSettingsAppearance'](arg1, arg2);
}

export function SaveSettingsEditors(arg1) {
  return window['go']['main']['App']['SaveSettingsEditors'](arg1);
}

export function SaveSettingsForester(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettingsForester'](arg1, arg2, arg3);
}

export function SaveSettingsProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettingsProfile'](arg1, arg2, arg3);
}

export function SaveSettingsRepos(arg1) {
  return window['go']['main']['App']['SaveSettingsRepos'](arg1);
}

export function SetRepoUser(arg1) {
  return window['go']['main']['App']['SetRepoUser'](arg1);
}
